### ISSUE TITLE
All tasks - certificate authentication parameters should be dynamic

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.HTTP#35]
This is valid for all HTTP tasks we have - currently if the client certificate is selected as auth method we show parameters such as "File path" and "base64" and "thumbprint". This is confusing and we should introduce a new dropdown selection parameter called "CertificateSource" with options "File", "String", "CertificateStore".

**Comment by MatteoDelOmbra** [comment]
Isn't same case to fix in https://github.com/FrendsPlatform/Frends.Web ? Or is it some deprecated task (if so, shouldn't it be flagged as deprecated?
